"""empty message

Revision ID: 561990120ebf
Revises: c5b4b3f0c1e8
Create Date: 2019-04-01 13:39:20.773959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '561990120ebf'
down_revision = 'c5b4b3f0c1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_manage_access_level', table_name='manage_access')
    op.drop_column('manage_access', 'level')
    op.add_column('manage_user', sa.Column('is_super', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manage_user', 'is_super')
    op.add_column('manage_access', sa.Column('level', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.create_index('ix_manage_access_level', 'manage_access', ['level'], unique=False)
    # ### end Alembic commands ###
