"""empty message

Revision ID: c5b4b3f0c1e8
Revises: 67da62d42829
Create Date: 2019-03-31 22:33:18.132750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b4b3f0c1e8'
down_revision = '67da62d42829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manage_user', sa.Column('status', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manage_user', 'status')
    # ### end Alembic commands ###
